FROM python:3.11-slim

WORKDIR /app

# Устанавливаем системные зависимости (если нужны)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
# Копируем зависимости и устанавливаем
COPY pyproject.toml .
RUN uv sync --no-dev

# Копируем код
COPY . .

# Создаем пользователя не-root для безопасности
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser



CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]