"""add parent id in users

Revision ID: b3d85c09b35d
Revises: 0e0f19d809e6
Create Date: 2026-09-22 16:09:29.786309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d85c09b35d'
down_revision: Union[str, Sequence[str], None] = '0e0f19d809e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_parent_id'), 'users', ['parent_id'], unique=False)
    op.create_foreign_key('users_parent_id_fkey', 'users', 'users', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_parent_id_fkey', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_parent_id'), table_name='users')
    op.drop_column('users', 'parent_id')
    # ### end Alembic commands ###
