"""add media type in check and add new fk for table PermissionCondition

Revision ID: 8eb95ca4ce32
Revises: b53ab2218cd9
Create Date: 2026-09-28 18:06:54.526490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb95ca4ce32'
down_revision: Union[str, Sequence[str], None] = 'b53ab2218cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_conditions', sa.Column('media_type_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_permission_condition'), 'permission_conditions', type_='unique')
    op.create_unique_constraint('uq_permission_condition', 'permission_conditions', ['permission_id', 'type', 'effect', 'category_id', 'role_id', 'media_type_id'])
    op.create_foreign_key("fk_permission_condition_media_type_id", 'permission_conditions', 'media_types', ['media_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ck_permission_condition_type', 'permission_conditions', type_='check')
    op.create_check_constraint(
        'ck_permission_condition_type',
        'permission_conditions',
        """
        (type = 'ALL'      AND category_id IS NULL AND role_id IS NULL AND media_type_id IS NULL) OR
        (type = 'CATEGORY' AND category_id IS NOT NULL AND role_id IS NULL AND media_type_id IS NULL) OR
        (type = 'ROLE'     AND role_id IS NOT NULL AND category_id IS NULL AND media_type_id IS NULL) OR
        (type = 'CREATOR'  AND category_id IS NULL AND role_id IS NULL AND media_type_id IS NULL) OR
        (type = 'SUBTREE'  AND category_id IS NULL AND role_id IS NULL AND media_type_id IS NULL) OR
        (type = 'MEDIA'    AND category_id IS NULL AND role_id IS NULL AND media_type_id IS NOT NULL)
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM permission_conditions WHERE type = 'MEDIA'")
    # The old check constraint (below) does not know about MEDIA type.
    # Delete MEDIA rows before re-applying it, otherwise CheckViolation.
    # NOTE: destructive — MEDIA conditions are lost on downgrade.
    op.drop_constraint('ck_permission_condition_type', 'permission_conditions', type_='check')
    op.create_check_constraint(
        'ck_permission_condition_type',
        'permission_conditions',
        """
        (type = 'ALL'      AND category_id IS NULL AND role_id IS NULL) OR
        (type = 'CATEGORY' AND category_id IS NOT NULL AND role_id IS NULL) OR
        (type = 'ROLE'     AND role_id IS NOT NULL AND category_id IS NULL) OR
        (type = 'CREATOR'  AND category_id IS NULL AND role_id IS NULL) OR
        (type = 'SUBTREE'  AND category_id IS NULL AND role_id IS NULL)
        """,
    )
    op.drop_constraint("fk_permission_condition_media_type_id", 'permission_conditions', type_='foreignkey')
    op.drop_constraint('uq_permission_condition', 'permission_conditions', type_='unique')
    op.create_unique_constraint('uq_permission_condition', 'permission_conditions', ['permission_id', 'type', 'effect', 'category_id', 'role_id'])
    op.drop_column('permission_conditions', 'media_type_id')
    