"""fix uuid for orgs

Revision ID: aac1e76d37e4
Revises: 80d93f08ae05
Create Date: 2026-10-07 17:18:20.941197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac1e76d37e4'
down_revision: Union[str, Sequence[str], None] = '80d93f08ae05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'id', server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'id', server_default=None)
    # ### end Alembic commands ###
