"""add sessions table

Revision ID: 73bf8be58d0e
Revises: e1a5a2be8dcc
Create Date: 2026-09-16 23:32:46.367404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bf8be58d0e'
down_revision: Union[str, Sequence[str], None] = 'e1a5a2be8dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_session_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_session_token_hash', 'sessions', ['token_hash'], unique=False)
    op.create_index('ix_session_user_id', 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_user_id', table_name='sessions')
    op.drop_index('ix_session_token_hash', table_name='sessions')
    op.drop_index('ix_session_expires_at', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
