"""Add VisualType table for colors

Revision ID: d4c8b286fbe3
Revises: 2d875d223415
Create Date: 2026-09-13 21:39:40.000901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c8b286fbe3'
down_revision: Union[str, Sequence[str], None] = '2d875d223415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_visual_type_code', 'visual_types', ['code'], unique=False)
    op.create_table('color_visual_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=False),
    sa.Column('visual_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visual_type_id'], ['visual_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_id', 'visual_type_id', name='uq_color_visual_type')
    )
    op.create_index('ix_color_visual_type_color_id', 'color_visual_types', ['color_id'], unique=False)
    op.create_index('ix_color_visual_type_visual_type_id', 'color_visual_types', ['visual_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_color_visual_type_visual_type_id', table_name='color_visual_types')
    op.drop_index('ix_color_visual_type_color_id', table_name='color_visual_types')
    op.drop_table('color_visual_types')
    op.drop_index('ix_visual_type_code', table_name='visual_types')
    op.drop_table('visual_types')
    # ### end Alembic commands ###
