"""remove product_id and variant_id from gallery_rule_conditions, add permission_condition index

Revision ID: e1a5a2be8dcc
Revises: d4c8b286fbe3
Create Date: 2026-09-16 20:15:10.817675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a5a2be8dcc'
down_revision: Union[str, Sequence[str], None] = 'd4c8b286fbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_rule_condition_product_id'), table_name='gallery_rule_conditions')
    op.drop_index(op.f('ix_gallery_rule_condition_variant_id'), table_name='gallery_rule_conditions')
    op.drop_constraint(op.f('gallery_rule_conditions_variant_id_fkey'), 'gallery_rule_conditions', type_='foreignkey')
    op.drop_constraint(op.f('gallery_rule_conditions_product_id_fkey'), 'gallery_rule_conditions', type_='foreignkey')
    op.drop_column('gallery_rule_conditions', 'product_id')
    op.drop_column('gallery_rule_conditions', 'variant_id')
    op.create_index('ix_permission_condition_permission_id', 'permission_conditions', ['permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permission_condition_permission_id', table_name='permission_conditions')
    op.add_column('gallery_rule_conditions', sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('gallery_rule_conditions', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('gallery_rule_conditions_product_id_fkey'), 'gallery_rule_conditions', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('gallery_rule_conditions_variant_id_fkey'), 'gallery_rule_conditions', 'product_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_gallery_rule_condition_variant_id'), 'gallery_rule_conditions', ['variant_id'], unique=False)
    op.create_index(op.f('ix_gallery_rule_condition_product_id'), 'gallery_rule_conditions', ['product_id'], unique=False)
    # ### end Alembic commands ###
