"""delete is_sustem column in permission

Revision ID: 80d93f08ae05
Revises: 01a409a18cd2
Create Date: 2026-09-29 20:17:47.039521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d93f08ae05'
down_revision: Union[str, Sequence[str], None] = '01a409a18cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_permission_forbidden_combinations', 'permissions', type_='check')
    op.drop_column('permissions', 'is_system')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'permissions',
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'),
)
    op.create_check_constraint(
        'ck_permission_forbidden_combinations',
        'permissions',
        """
        NOT (
                        (resource = 'USERS'      AND action = 'ARCHIVE') OR
                        (resource = 'PROJECTS'   AND action IN ('IMPORT', 'EXPORT')) OR
                        (resource = 'CUSTOMERS'  AND action = 'ARCHIVE') OR
                        (resource = 'MEDIA'      AND action IN ('ARCHIVE', 'EXPORT', 'IMPORT')) OR
                        (resource = 'CALCULATOR' AND action IN ('ARCHIVE', 'IMPORT')) OR
                        (resource = 'SETTINGS'   AND action IN ('CREATE', 'DELETE', 'ARCHIVE', 'EXPORT', 'IMPORT')) OR
                        (resource = 'AUDIT_LOG'  AND action IN ('CREATE', 'UPDATE', 'DELETE', 'ARCHIVE', 'IMPORT'))
                    )
        """,)
    # ### end Alembic commands ###
