"""Add gallery, user media, color/material groups; remove template_item_media

Revision ID: 5cb49006e8af
Revises: 2b1eef33ad12
Create Date: 2026-09-13 20:07:08.039196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cb49006e8af'
down_revision: Union[str, Sequence[str], None] = '2b1eef33ad12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('gallery_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_gallery_rule_code', 'gallery_rules', ['code'], unique=False)
    op.create_index('ix_gallery_rule_is_active', 'gallery_rules', ['is_active'], unique=False)
    op.create_table('material_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('category_color_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('color_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['color_group_id'], ['color_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'color_group_id', name='uq_category_color_group')
    )
    op.create_index('ix_category_color_group_category_id', 'category_color_groups', ['category_id'], unique=False)
    op.create_index('ix_category_color_group_group_id', 'category_color_groups', ['color_group_id'], unique=False)
    op.create_table('category_material_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('material_group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_group_id'], ['material_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'material_group_id', name='uq_category_material_group')
    )
    op.create_index('ix_category_material_group_category_id', 'category_material_groups', ['category_id'], unique=False)
    op.create_index('ix_category_material_group_group_id', 'category_material_groups', ['material_group_id'], unique=False)
    op.create_table('template_gallery',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('media_type_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['gallery_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_gallery_media_file_id', 'template_gallery', ['media_file_id'], unique=False)
    op.create_index('ix_template_gallery_rule_id', 'template_gallery', ['rule_id'], unique=False)
    op.create_index('ix_template_gallery_template_id', 'template_gallery', ['template_id'], unique=False)
    op.create_table('user_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('media_type_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_type_id', name='uq_user_media_user_type')
    )
    op.create_index('ix_user_media_media_file_id', 'user_media', ['media_file_id'], unique=False)
    op.create_index('ix_user_media_media_type_id', 'user_media', ['media_type_id'], unique=False)
    op.create_index('ix_user_media_user_id', 'user_media', ['user_id'], unique=False)
    op.create_table('gallery_rule_conditions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['gallery_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gallery_rule_condition_category_id', 'gallery_rule_conditions', ['category_id'], unique=False)
    op.create_index('ix_gallery_rule_condition_product_id', 'gallery_rule_conditions', ['product_id'], unique=False)
    op.create_index('ix_gallery_rule_condition_rule_id', 'gallery_rule_conditions', ['rule_id'], unique=False)
    op.create_index('ix_gallery_rule_condition_variant_id', 'gallery_rule_conditions', ['variant_id'], unique=False)
    op.drop_index(op.f('ix_quote_glass_media_glass_item_id'), table_name='quote_glass_media')
    op.drop_index(op.f('ix_quote_glass_media_media_file_id'), table_name='quote_glass_media')
    op.drop_table('quote_glass_media')
    op.drop_index(op.f('ix_quote_glass_item_quote_item_id'), table_name='quote_glass_items')
    op.drop_index(op.f('ix_quote_glass_item_version_id'), table_name='quote_glass_items')
    op.drop_table('quote_glass_items')
    op.drop_index(op.f('ix_template_item_media_item_id'), table_name='template_item_media')
    op.drop_index(op.f('ix_template_item_media_media_file_id'), table_name='template_item_media')
    op.drop_table('template_item_media')
    op.add_column('colors', sa.Column('group_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('colors_name_key'), 'colors', type_='unique')
    op.create_index('ix_color_group_id', 'colors', ['group_id'], unique=False)
    op.create_foreign_key('fk_colors_group_id', 'colors', 'color_groups', ['group_id'], ['id'], ondelete='RESTRICT')
    op.add_column('materials', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_index('ix_material_group_id', 'materials', ['group_id'], unique=False)
    op.create_foreign_key('fk_materials_group_id', 'materials', 'material_groups', ['group_id'], ['id'], ondelete='RESTRICT')
    op.add_column('media_files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('media_types', sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('media_types', 'is_system')
    op.drop_column('media_files', 'updated_at')
    op.drop_constraint('fk_materials_group_id', 'materials', type_='foreignkey')
    op.drop_index('ix_material_group_id', table_name='materials')
    op.drop_column('materials', 'group_id')
    op.drop_constraint('fk_colors_group_id', 'colors', type_='foreignkey')
    op.drop_index('ix_color_group_id', table_name='colors')
    op.create_unique_constraint(op.f('colors_name_key'), 'colors', ['name'])
    op.drop_column('colors', 'group_id')
    op.create_table('template_item_media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('template_item_media_media_file_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], name=op.f('template_item_media_media_type_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_item_id'], ['template_items.id'], name=op.f('template_item_media_template_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('template_item_media_pkey'))
    )
    op.create_index(op.f('ix_template_item_media_media_file_id'), 'template_item_media', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_template_item_media_item_id'), 'template_item_media', ['template_item_id'], unique=False)
    op.create_table('quote_glass_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quote_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quote_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('width_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('height_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('thickness_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('glass_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('area_m2', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_items.id'], name=op.f('quote_glass_items_quote_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], name=op.f('quote_glass_items_quote_version_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_glass_items_pkey'))
    )
    op.create_index(op.f('ix_quote_glass_item_version_id'), 'quote_glass_items', ['quote_version_id'], unique=False)
    op.create_index(op.f('ix_quote_glass_item_quote_item_id'), 'quote_glass_items', ['quote_item_id'], unique=False)
    op.create_table('quote_glass_media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quote_glass_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('quote_glass_media_media_file_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_glass_item_id'], ['quote_glass_items.id'], name=op.f('quote_glass_media_quote_glass_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quote_glass_media_pkey'))
    )
    op.create_index(op.f('ix_quote_glass_media_media_file_id'), 'quote_glass_media', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_quote_glass_media_glass_item_id'), 'quote_glass_media', ['quote_glass_item_id'], unique=False)
    op.drop_index('ix_gallery_rule_condition_variant_id', table_name='gallery_rule_conditions')
    op.drop_index('ix_gallery_rule_condition_rule_id', table_name='gallery_rule_conditions')
    op.drop_index('ix_gallery_rule_condition_product_id', table_name='gallery_rule_conditions')
    op.drop_index('ix_gallery_rule_condition_category_id', table_name='gallery_rule_conditions')
    op.drop_table('gallery_rule_conditions')
    op.drop_index('ix_user_media_user_id', table_name='user_media')
    op.drop_index('ix_user_media_media_type_id', table_name='user_media')
    op.drop_index('ix_user_media_media_file_id', table_name='user_media')
    op.drop_table('user_media')
    op.drop_index('ix_template_gallery_template_id', table_name='template_gallery')
    op.drop_index('ix_template_gallery_rule_id', table_name='template_gallery')
    op.drop_index('ix_template_gallery_media_file_id', table_name='template_gallery')
    op.drop_table('template_gallery')
    op.drop_index('ix_category_material_group_group_id', table_name='category_material_groups')
    op.drop_index('ix_category_material_group_category_id', table_name='category_material_groups')
    op.drop_table('category_material_groups')
    op.drop_index('ix_category_color_group_group_id', table_name='category_color_groups')
    op.drop_index('ix_category_color_group_category_id', table_name='category_color_groups')
    op.drop_table('category_color_groups')
    op.drop_table('material_groups')
    op.drop_index('ix_gallery_rule_is_active', table_name='gallery_rules')
    op.drop_index('ix_gallery_rule_code', table_name='gallery_rules')
    op.drop_table('gallery_rules')
    op.drop_table('color_groups')
    # ### end Alembic commands ###
