"""Add binding_type

Revision ID: 2d875d223415
Revises: 5cb49006e8af
Create Date: 2026-09-13 20:53:35.965445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d875d223415'
down_revision: Union[str, Sequence[str], None] = '5cb49006e8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binding_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_binding_type_code', 'binding_types', ['code'], unique=False)
    op.add_column('templates', sa.Column('binding_type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'templates', 'binding_types', ['binding_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates_binding_type_id_fkey', 'templates', type_='foreignkey')
    op.drop_column('templates', 'binding_type_id')
    op.drop_index('ix_binding_type_code', table_name='binding_types')
    op.drop_table('binding_types')
    # ### end Alembic commands ###
