"""role owner nullable for system roles

Revision ID: a9a1c5ca1c0e
Revises: 58cfd7aa86a8
Create Date: 2026-09-21 23:45:10.986627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a1c5ca1c0e'
down_revision: Union[str, Sequence[str], None] = '58cfd7aa86a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_role_owner_name'), 'roles', type_='unique')
    op.create_index('uq_role_owner_name', 'roles', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('owner_id IS NOT NULL'))
    op.create_index('uq_role_system_name', 'roles', ['name'], unique=True, postgresql_where=sa.text('owner_id IS NULL'))
    op.create_check_constraint(
        'ck_role_owner_system',
        'roles',
        "(is_system = true AND owner_id IS NULL) OR "
        "(is_system = false AND owner_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_role_owner_system', 'roles', type_='check')
    op.drop_index('uq_role_system_name', table_name='roles', postgresql_where=sa.text('owner_id IS NULL'))
    op.drop_index('uq_role_owner_name', table_name='roles', postgresql_where=sa.text('owner_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_role_owner_name'), 'roles', ['owner_id', 'name'])
    op.alter_column('roles', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
