"""modify role tables 2

Revision ID: 58cfd7aa86a8
Revises: 016927572017
Create Date: 2026-09-21 20:52:32.844054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cfd7aa86a8'
down_revision: Union[str, Sequence[str], None] = '016927572017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        CREATE TYPE permissionaction_new AS ENUM (
            'CREATE', 'READ', 'UPDATE', 'DELETE', 'ARCHIVE', 'EXPORT', 'IMPORT'
        )
    """)

    # 2. Удалить старые данные, которых нет в новом типе
    op.execute("""
        DELETE FROM permissions
        WHERE action::text NOT IN (
            'CREATE', 'READ', 'UPDATE', 'DELETE', 'ARCHIVE', 'EXPORT', 'IMPORT'
        )
    """)

    # 3. Перевести колонку на новый тип
    op.execute("""
        ALTER TABLE permissions
        ALTER COLUMN action TYPE permissionaction_new
        USING action::text::permissionaction_new
    """)

    # 4. Удалить старый тип и переименовать новый
    op.execute("DROP TYPE permissionaction")
    op.execute("ALTER TYPE permissionaction_new RENAME TO permissionaction")
    op.drop_constraint('roles_code_key', 'roles', type_='unique')
    op.drop_column('roles', 'code')
    op.execute("DROP TYPE IF EXISTS permissionscope")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_roles_owner_id'), 'roles', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_role_owner_name', 'roles', ['owner_id', 'name'])
    op.create_foreign_key('fk_roles_owner_id', 'roles', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_direct_permission_condition_id'), table_name='user_direct_permissions')
    op.create_index('ix_user_direct_permission_user_id', 'user_direct_permissions', ['user_id'], unique=False)
    op.create_index('ix_user_permission_user_id', 'user_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE permission_conditions
        DROP CONSTRAINT IF EXISTS ck_permission_condition_type;
    """)
    op.create_check_constraint(
        'ck_permission_condition_type',
        'permission_conditions',
        """
        (type = 'ALL'      AND category_id IS NULL AND role_id IS NULL) OR
        (type = 'CATEGORY' AND category_id IS NOT NULL AND role_id IS NULL) OR
        (type = 'ROLE'     AND role_id IS NOT NULL AND category_id IS NULL) OR
        (type = 'CREATOR'  AND category_id IS NULL AND role_id IS NULL) OR
        (type = 'SUBTREE'  AND category_id IS NULL AND role_id IS NULL)
        """,
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
        ALTER TABLE permission_conditions
        DROP CONSTRAINT IF EXISTS ck_permission_condition_type;
    """)
    op.create_check_constraint(
        'ck_permission_condition_type',
        'permission_conditions',
        """
        (type = 'ALL'      AND category_id IS NULL AND role_id IS NULL) OR
        (type = 'CATEGORY' AND category_id IS NOT NULL AND role_id IS NULL) OR
        (type = 'ROLE'     AND role_id IS NOT NULL AND category_id IS NULL) OR
        (type = 'CREATOR'  AND category_id IS NULL AND role_id IS NULL)
        """,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_permission_user_id', table_name='user_permissions')
    op.drop_index('ix_user_direct_permission_user_id', table_name='user_direct_permissions')
    op.create_index(op.f('ix_user_direct_permission_condition_id'), 'user_direct_permissions', ['condition_id'], unique=False)
    op.drop_constraint('fk_roles_owner_id', 'roles', type_='foreignkey')
    op.drop_constraint('uq_role_owner_name', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_owner_id'), table_name='roles')
    op.drop_column('roles', 'owner_id')
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE permissionscope AS ENUM ('ALL', 'OWN', 'DEPARTMENT', 'ASSIGNED', 'SPECIFIC');
        EXCEPTION WHEN duplicate_object THEN null;
        END $$;
    """)
    op.add_column('roles', sa.Column('code', sa.String(50), nullable=False))
    op.create_unique_constraint('roles_code_key', 'roles', ['code'])
    op.execute("""
        CREATE TYPE permissionaction_old AS ENUM (
            'CREATE', 'READ', 'UPDATE', 'DELETE', 'ARCHIVE', 'RESTORE',
            'EXPORT', 'IMPORT', 'APPROVE', 'ASSIGN', 'MANAGE'
        )
    """)

    # 2. Перевести колонку
    op.execute("""
        ALTER TABLE permissions
        ALTER COLUMN action TYPE permissionaction_old
        USING action::text::permissionaction_old
    """)

    # 3. Удалить текущий тип и переименовать старый
    op.execute("DROP TYPE permissionaction")
    op.execute("ALTER TYPE permissionaction_old RENAME TO permissionaction")
    # ### end Alembic commands ###
