"""add media in type of PermissionCondition

Revision ID: b53ab2218cd9
Revises: edecd9cd09db
Create Date: 2026-09-28 17:52:22.893892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53ab2218cd9'
down_revision: Union[str, Sequence[str], None] = 'edecd9cd09db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE conditiontype ADD VALUE IF NOT EXISTS 'MEDIA'")


def downgrade() -> None:
    """Downgrade schema."""
    pass
    # NOTE: Postgres does not support removing values from an enum type.
    # 'MEDIA' remains in the enum after downgrade. It is harmless: no rows
    # should have type='MEDIA' after the downgrade anyway (the check constraint
    # below rejects them, and we drop the column above).
    