"""Initial migration

Revision ID: a8ca5a662ea7
Revises: 
Create Date: 2026-09-11 00:34:46.600904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8ca5a662ea7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('colors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.Enum('USERS', 'ROLES', 'PRODUCTS', 'CATEGORIES', 'TEMPLATES', 'QUOTES', 'PROJECTS', 'CUSTOMERS', 'SUPPLIERS', 'MEDIA', 'CALCULATOR', 'SETTINGS', 'AUDIT_LOG', name='permissionresource'), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'ARCHIVE', 'RESTORE', 'EXPORT', 'IMPORT', 'APPROVE', 'ASSIGN', 'MANAGE', name='permissionaction'), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'OWN', 'DEPARTMENT', 'ASSIGNED', 'SPECIFIC', name='permissionscope'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_permission_code', 'permissions', ['code'], unique=False)
    op.create_index('ix_permission_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.create_table('project_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('usage_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.Enum('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'OPTION', name='attributedatatype'), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('category_media_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('media_type_id', sa.UUID(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_usage_roles',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('usage_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_role_id'], ['usage_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'usage_role_id')
    )
    op.create_table('customer_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DELIVERY', 'BILLING', 'OTHER', name='addresstype'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ROLE', 'CATEGORY', 'CREATOR', 'CUSTOM', name='permissionconditiontype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DISCONTINUED', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['project_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_project_customer_id', 'projects', ['customer_id'], unique=False)
    op.create_index('ix_project_status_id', 'projects', ['status_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index('ix_role_permission_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permission_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('STANDARD', 'BINDING', name='templatetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission')
    )
    op.create_index('ix_user_permission_user_id', 'user_permissions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('attribute_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_attributes',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id')
    )
    op.create_table('product_usage_roles',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('usage_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usage_role_id'], ['usage_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'usage_role_id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('internal_sku', sa.String(length=100), nullable=True),
    sa.Column('name_override', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DISCONTINUED', name='productvariantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_sku'),
    sa.UniqueConstraint('product_id', 'color_id', 'material_id', name='uq_variant_product_color_material')
    )
    op.create_index('ix_variant_color_id', 'product_variants', ['color_id'], unique=False)
    op.create_index('ix_variant_material_id', 'product_variants', ['material_id'], unique=False)
    op.create_index('ix_variant_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('ix_variant_status', 'product_variants', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'APPROVED', 'REJECTED', 'ARCHIVED', name='quotestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_project_id', 'quotes', ['project_id'], unique=False)
    op.create_index('ix_quote_status', 'quotes', ['status'], unique=False)
    op.create_table('template_media_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('media_type_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_media_rule_media_type_id', 'template_media_rules', ['media_type_id'], unique=False)
    op.create_index('ix_template_media_rule_template_id', 'template_media_rules', ['template_id'], unique=False)
    op.create_table('product_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'DRAWING', 'SCHEME', name='productmediatype'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('global_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('global_markup_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('customer_name_snapshot', sa.Text(), nullable=True),
    sa.Column('customer_phone_snapshot', sa.Text(), nullable=True),
    sa.Column('customer_email_snapshot', sa.Text(), nullable=True),
    sa.Column('delivery_address_snapshot', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_version_created_at', 'quote_versions', ['created_at'], unique=False)
    op.create_index('ix_quote_version_quote_id', 'quote_versions', ['quote_id'], unique=False)
    op.create_table('supplier_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('minimum_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'supplier_sku', name='uq_supplier_sku')
    )
    op.create_table('variant_attribute_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value_string', sa.String(length=500), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_decimal', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_option_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_option_id'], ['attribute_options.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant_usage_roles',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('usage_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usage_role_id'], ['usage_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'usage_role_id')
    )
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('quote_version_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('COMMERCIAL_PROPOSAL', name='documenttype'), nullable=False),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_document_generated_at', 'generated_documents', ['generated_at'], unique=False)
    op.create_index('ix_generated_document_project_id', 'generated_documents', ['project_id'], unique=False)
    op.create_index('ix_generated_document_quote_id', 'generated_documents', ['quote_id'], unique=False)
    op.create_index('ix_generated_document_quote_version_id', 'generated_documents', ['quote_version_id'], unique=False)
    op.create_index('ix_generated_document_type', 'generated_documents', ['type'], unique=False)
    op.create_table('quote_item_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_version_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TEMPLATE', 'BINDING', 'MANUAL', name='quoteitemgrouptype'), nullable=False),
    sa.Column('source_template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_item_group_version_id', 'quote_item_groups', ['quote_version_id'], unique=False)
    op.create_table('supplier_variant_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_variant_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_variant_id'], ['supplier_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('preferred_supplier_variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preferred_supplier_variant_id'], ['supplier_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_item_template_id', 'template_items', ['template_id'], unique=False)
    op.create_index('ix_template_item_variant_id', 'template_items', ['variant_id'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_version_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('PRODUCT', 'TEMPLATE', 'MANUAL', name='quoteitemsourcetype'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('supplier_variant_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('template_item_id', sa.UUID(), nullable=True),
    sa.Column('name_snapshot', sa.Text(), nullable=False),
    sa.Column('supplier_name_snapshot', sa.Text(), nullable=True),
    sa.Column('supplier_sku_snapshot', sa.Text(), nullable=True),
    sa.Column('color_snapshot', sa.Text(), nullable=True),
    sa.Column('material_snapshot', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('purchase_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('base_sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('manual_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['quote_item_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_variant_id'], ['supplier_variants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_item_id'], ['template_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_item_group_id', 'quote_items', ['group_id'], unique=False)
    op.create_index('ix_quote_item_product_id', 'quote_items', ['product_id'], unique=False)
    op.create_index('ix_quote_item_variant_id', 'quote_items', ['variant_id'], unique=False)
    op.create_index('ix_quote_item_version_id', 'quote_items', ['quote_version_id'], unique=False)
    op.create_table('template_item_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_item_id', sa.UUID(), nullable=False),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('media_type_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['media_type_id'], ['media_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_item_id'], ['template_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_template_item_media_item_id', 'template_item_media', ['template_item_id'], unique=False)
    op.create_index('ix_template_item_media_media_file_id', 'template_item_media', ['media_file_id'], unique=False)
    op.create_table('quote_glass_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_version_id', sa.UUID(), nullable=False),
    sa.Column('quote_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('glass_type', sa.String(length=100), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_glass_item_quote_item_id', 'quote_glass_items', ['quote_item_id'], unique=False)
    op.create_index('ix_quote_glass_item_version_id', 'quote_glass_items', ['quote_version_id'], unique=False)
    op.create_table('quote_glass_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_glass_item_id', sa.UUID(), nullable=False),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_glass_item_id'], ['quote_glass_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_glass_media_glass_item_id', 'quote_glass_media', ['quote_glass_item_id'], unique=False)
    op.create_index('ix_quote_glass_media_media_file_id', 'quote_glass_media', ['media_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_glass_media_media_file_id', table_name='quote_glass_media')
    op.drop_index('ix_quote_glass_media_glass_item_id', table_name='quote_glass_media')
    op.drop_table('quote_glass_media')
    op.drop_index('ix_quote_glass_item_version_id', table_name='quote_glass_items')
    op.drop_index('ix_quote_glass_item_quote_item_id', table_name='quote_glass_items')
    op.drop_table('quote_glass_items')
    op.drop_index('ix_template_item_media_media_file_id', table_name='template_item_media')
    op.drop_index('ix_template_item_media_item_id', table_name='template_item_media')
    op.drop_table('template_item_media')
    op.drop_index('ix_quote_item_version_id', table_name='quote_items')
    op.drop_index('ix_quote_item_variant_id', table_name='quote_items')
    op.drop_index('ix_quote_item_product_id', table_name='quote_items')
    op.drop_index('ix_quote_item_group_id', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index('ix_template_item_variant_id', table_name='template_items')
    op.drop_index('ix_template_item_template_id', table_name='template_items')
    op.drop_table('template_items')
    op.drop_table('supplier_variant_prices')
    op.drop_index('ix_quote_item_group_version_id', table_name='quote_item_groups')
    op.drop_table('quote_item_groups')
    op.drop_index('ix_generated_document_type', table_name='generated_documents')
    op.drop_index('ix_generated_document_quote_version_id', table_name='generated_documents')
    op.drop_index('ix_generated_document_quote_id', table_name='generated_documents')
    op.drop_index('ix_generated_document_project_id', table_name='generated_documents')
    op.drop_index('ix_generated_document_generated_at', table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_table('variant_usage_roles')
    op.drop_table('variant_attribute_values')
    op.drop_table('supplier_variants')
    op.drop_index('ix_quote_version_quote_id', table_name='quote_versions')
    op.drop_index('ix_quote_version_created_at', table_name='quote_versions')
    op.drop_table('quote_versions')
    op.drop_table('product_media')
    op.drop_index('ix_template_media_rule_template_id', table_name='template_media_rules')
    op.drop_index('ix_template_media_rule_media_type_id', table_name='template_media_rules')
    op.drop_table('template_media_rules')
    op.drop_index('ix_quote_status', table_name='quotes')
    op.drop_index('ix_quote_project_id', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_variant_status', table_name='product_variants')
    op.drop_index('ix_variant_product_id', table_name='product_variants')
    op.drop_index('ix_variant_material_id', table_name='product_variants')
    op.drop_index('ix_variant_color_id', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_table('product_usage_roles')
    op.drop_table('category_attributes')
    op.drop_table('attribute_options')
    op.drop_table('user_roles')
    op.drop_index('ix_user_permission_user_id', table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_table('templates')
    op.drop_index('ix_role_permission_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permission_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_project_status_id', table_name='projects')
    op.drop_index('ix_project_customer_id', table_name='projects')
    op.drop_table('projects')
    op.drop_table('products')
    op.drop_table('permission_conditions')
    op.drop_table('media_files')
    op.drop_table('customer_addresses')
    op.drop_table('category_usage_roles')
    op.drop_table('category_media_rules')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('usage_roles')
    op.drop_table('units')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('project_statuses')
    op.drop_index('ix_permission_resource_action', table_name='permissions')
    op.drop_index('ix_permission_code', table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('media_types')
    op.drop_table('materials')
    op.drop_table('customers')
    op.drop_table('colors')
    op.drop_table('categories')
      # Удалить все enum-типы
    op.execute("DROP TYPE IF EXISTS permissionresource")
    op.execute("DROP TYPE IF EXISTS permissionaction")
    op.execute("DROP TYPE IF EXISTS permissionscope")
    op.execute("DROP TYPE IF EXISTS attributedatatype")
    op.execute("DROP TYPE IF EXISTS addresstype")
    op.execute("DROP TYPE IF EXISTS productstatus")
    op.execute("DROP TYPE IF EXISTS productvariantstatus")
    op.execute("DROP TYPE IF EXISTS templatetype")
    op.execute("DROP TYPE IF EXISTS productmediatype")
    op.execute("DROP TYPE IF EXISTS documenttype")
    op.execute("DROP TYPE IF EXISTS quoteitemgrouptype")
    op.execute("DROP TYPE IF EXISTS quoteitemsourcetype")
    op.execute("DROP TYPE IF EXISTS quotestatus")
    op.execute("DROP TYPE IF EXISTS permissionconditiontype")
    # ### end Alembic commands ###
