from app.repositories.protocols.base import (
    ReadRepositoryProtocol,
    WriteRepositoryProtocol,
)
from app.repositories.protocols.system import (
    OrganizationReadRepositoryProtocol,
    OrganizationWriteRepositoryProtocol,
    PermissionConditionReadRepositoryProtocol,
    PermissionConditionWriteRepositoryProtocol,
    PermissionReadRepositoryProtocol,
    PermissionWriteRepositoryProtocol,
    RolePermissionReadRepositoryProtocol,
    RolePermissionWriteRepositoryProtocol,
    RoleReadRepositoryProtocol,
    RoleWriteRepositoryProtocol,
    UserDirectPermissionReadRepositoryProtocol,
    UserDirectPermissionRepositoryProtocol,
    UserDirectPermissionWriteRepositoryProtocol,
    UserPermissionReadRepositoryProtocol,
    UserPermissionRepositoryProtocol,
    UserPermissionWriteRepositoryProtocol,
    UserReadRepositoryProtocol,
    UserRoleReadRepositoryProtocol,
    UserRoleWriteRepositoryProtocol,
    UserWriteRepositoryProtocol,
)

# from app.repositories.protocols.role import (
#     RoleReadRepositoryProtocol,
#     RoleWriteRepositoryProtocol,
# )

__all__ = [
    "ReadRepositoryProtocol",
    "WriteRepositoryProtocol",
    "UserReadRepositoryProtocol",
    "UserWriteRepositoryProtocol",
    # "RoleReadRepositoryProtocol",
    # "RoleWriteRepositoryProtocol",
    "OrganizationReadRepositoryProtocol",
    "OrganizationWriteRepositoryProtocol",
    "PermissionReadRepositoryProtocol",
    "PermissionWriteRepositoryProtocol",
    "PermissionConditionReadRepositoryProtocol",
    "PermissionConditionWriteRepositoryProtocol",
    "RolePermissionReadRepositoryProtocol",
    "RolePermissionWriteRepositoryProtocol",
    "RoleReadRepositoryProtocol",
    "RoleWriteRepositoryProtocol",
    "UserPermissionReadRepositoryProtocol",
    "UserPermissionWriteRepositoryProtocol",
    "UserPermissionRepositoryProtocol",
    "UserRoleReadRepositoryProtocol",
    "UserRoleWriteRepositoryProtocol",
    "UserDirectPermissionReadRepositoryProtocol",
    "UserDirectPermissionWriteRepositoryProtocol",
    "UserDirectPermissionRepositoryProtocol",
]
